// <auto-generated />
using System;
using ElektronickePosudky.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ElektronickePosudky.Infrastructure.Migrations
{
    [DbContext(typeof(ElektronickePosudkyContext))]
    partial class ElektronickePosudkyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ElektronickePosudky.Domain.Entities.Ciselnik", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PlatnostDo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PlatnostOd")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Termx")
                        .HasColumnType("bit");

                    b.Property<string>("TermxId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TermxUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Verze")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ciselniky");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a14bffda-1149-4ec5-b79d-cdda839259c1"),
                            Kod = "STAV-RO",
                            PlatnostOd = new DateTime(2025, 4, 16, 11, 3, 35, 144, DateTimeKind.Utc).AddTicks(1512),
                            Termx = false,
                            Verze = "1"
                        },
                        new
                        {
                            Id = new Guid("a376442b-a991-4405-81fb-e923e7dde10a"),
                            Kod = "DRUH-PROHLIDKY",
                            PlatnostOd = new DateTime(2025, 4, 16, 11, 3, 35, 144, DateTimeKind.Utc).AddTicks(1512),
                            Termx = false,
                            Verze = "1"
                        },
                        new
                        {
                            Id = new Guid("aff0c688-3a22-46c8-8404-82c61101d642"),
                            Kod = "DRUH-POSUDKU",
                            PlatnostOd = new DateTime(2025, 4, 16, 11, 3, 35, 144, DateTimeKind.Utc).AddTicks(1512),
                            Termx = false,
                            Verze = "1"
                        },
                        new
                        {
                            Id = new Guid("599ce4bc-4222-42f1-a238-eaed3a4b0abd"),
                            Kod = "VYSLEDEK",
                            PlatnostOd = new DateTime(2025, 4, 16, 11, 3, 35, 144, DateTimeKind.Utc).AddTicks(1512),
                            Termx = false,
                            Verze = "1"
                        },
                        new
                        {
                            Id = new Guid("9c599c83-1898-4d8a-aa18-3f867f8772a4"),
                            Kod = "SKUPINA-ZADATELE-RIDIC",
                            PlatnostOd = new DateTime(2025, 4, 16, 11, 3, 35, 144, DateTimeKind.Utc).AddTicks(1512),
                            Termx = false,
                            Verze = "1"
                        },
                        new
                        {
                            Id = new Guid("278605a9-2aa3-42d4-babe-f3d177fd2905"),
                            Kod = "ODBNORNOST",
                            PlatnostOd = new DateTime(2025, 4, 16, 11, 3, 35, 144, DateTimeKind.Utc).AddTicks(1512),
                            Termx = false,
                            Verze = "1"
                        },
                        new
                        {
                            Id = new Guid("d8142494-0f9d-4f6c-b1aa-2a42d071b5e8"),
                            Kod = "TYP-AKCE",
                            PlatnostOd = new DateTime(2025, 4, 16, 11, 3, 35, 144, DateTimeKind.Utc).AddTicks(1512),
                            Termx = false,
                            Verze = "1"
                        },
                        new
                        {
                            Id = new Guid("aae6530b-15f1-4469-b5f6-4f69592ad15d"),
                            Kod = "TYP-OPERACE",
                            PlatnostOd = new DateTime(2025, 4, 16, 11, 3, 35, 144, DateTimeKind.Utc).AddTicks(1512),
                            Termx = false,
                            Verze = "1"
                        });
                });

            modelBuilder.Entity("ElektronickePosudky.Domain.Entities.CiselnikPolozka", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CiselnikId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CiselnikKod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CiselnikVerze")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("RodicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Verze")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RodicId");

                    b.HasIndex("CiselnikId", "Kod")
                        .IsUnique();

                    b.ToTable("CiselnikPolozky");

                    b.HasData(
                        new
                        {
                            Id = new Guid("91c091e9-2d8a-454a-952e-61a37a6daa0c"),
                            CiselnikId = new Guid("a14bffda-1149-4ec5-b79d-cdda839259c1"),
                            CiselnikKod = "STAV-RO",
                            CiselnikVerze = "1",
                            Kod = "PLATNY",
                            Verze = "1"
                        },
                        new
                        {
                            Id = new Guid("06cefa04-8612-4dcf-b196-46d435f1718b"),
                            CiselnikId = new Guid("a14bffda-1149-4ec5-b79d-cdda839259c1"),
                            CiselnikKod = "STAV-RO",
                            CiselnikVerze = "1",
                            Kod = "ZNEPLATNENY",
                            Verze = "1"
                        },
                        new
                        {
                            Id = new Guid("69e3533b-2d45-4c6d-b8f8-2e2da0900cf5"),
                            CiselnikId = new Guid("a376442b-a991-4405-81fb-e923e7dde10a"),
                            CiselnikKod = "DRUH-PROHLIDKY",
                            CiselnikVerze = "1",
                            Kod = "VYCHOZI",
                            Verze = "1"
                        },
                        new
                        {
                            Id = new Guid("e5f46887-8028-4b62-9286-b2840eef4001"),
                            CiselnikId = new Guid("a376442b-a991-4405-81fb-e923e7dde10a"),
                            CiselnikKod = "DRUH-PROHLIDKY",
                            CiselnikVerze = "1",
                            Kod = "PERIODICKA",
                            Verze = "1"
                        },
                        new
                        {
                            Id = new Guid("f0c80839-a28f-4698-8ecd-1a8eb7cb7778"),
                            CiselnikId = new Guid("aff0c688-3a22-46c8-8404-82c61101d642"),
                            CiselnikKod = "DRUH-POSUDKU",
                            CiselnikVerze = "1",
                            Kod = "RIDICKY",
                            Verze = "1"
                        },
                        new
                        {
                            Id = new Guid("5dbb39ff-9d53-4c4a-956e-1e5fd88a0987"),
                            CiselnikId = new Guid("599ce4bc-4222-42f1-a238-eaed3a4b0abd"),
                            CiselnikKod = "VYSLEDEK",
                            CiselnikVerze = "1",
                            Kod = "ZPUSOBILY",
                            Verze = "1"
                        },
                        new
                        {
                            Id = new Guid("22743832-b044-4b23-bbb1-a109f7215467"),
                            CiselnikId = new Guid("599ce4bc-4222-42f1-a238-eaed3a4b0abd"),
                            CiselnikKod = "VYSLEDEK",
                            CiselnikVerze = "1",
                            Kod = "NEZPUSOBILY",
                            Verze = "1"
                        },
                        new
                        {
                            Id = new Guid("93f1f521-9613-47d4-b483-ce27821b7e5a"),
                            CiselnikId = new Guid("9c599c83-1898-4d8a-aa18-3f867f8772a4"),
                            CiselnikKod = "SKUPINA-ZADATELE-RIDIC",
                            CiselnikVerze = "1",
                            Kod = "A",
                            Verze = "1"
                        },
                        new
                        {
                            Id = new Guid("388f831b-4fb6-42e6-b049-35d14808db0b"),
                            CiselnikId = new Guid("9c599c83-1898-4d8a-aa18-3f867f8772a4"),
                            CiselnikKod = "SKUPINA-ZADATELE-RIDIC",
                            CiselnikVerze = "1",
                            Kod = "B",
                            Verze = "1"
                        },
                        new
                        {
                            Id = new Guid("82f7d36c-abd7-4e81-b29a-59873ac932a1"),
                            CiselnikId = new Guid("278605a9-2aa3-42d4-babe-f3d177fd2905"),
                            CiselnikKod = "ODBNORNOST",
                            CiselnikVerze = "1",
                            Kod = "INTERNI",
                            Verze = "1"
                        },
                        new
                        {
                            Id = new Guid("d8270f50-c7ad-4653-b893-b5897f9d52b0"),
                            CiselnikId = new Guid("278605a9-2aa3-42d4-babe-f3d177fd2905"),
                            CiselnikKod = "ODBNORNOST",
                            CiselnikVerze = "1",
                            Kod = "OKULISTA",
                            Verze = "1"
                        },
                        new
                        {
                            Id = new Guid("80bfdd5b-19fd-4c59-bd51-382a7cc97815"),
                            CiselnikId = new Guid("d8142494-0f9d-4f6c-b1aa-2a42d071b5e8"),
                            CiselnikKod = "TYP-AKCE",
                            CiselnikVerze = "1",
                            Kod = "VYDANI",
                            Verze = "1"
                        },
                        new
                        {
                            Id = new Guid("ea9d54c9-aa27-4aec-bd71-5e74f18318e5"),
                            CiselnikId = new Guid("aae6530b-15f1-4469-b5f6-4f69592ad15d"),
                            CiselnikKod = "TYP-OPERACE",
                            CiselnikVerze = "1",
                            Kod = "VYTVORENI",
                            Verze = "1"
                        },
                        new
                        {
                            Id = new Guid("ea4b809d-35eb-47c7-bbf8-91b4b3528914"),
                            CiselnikId = new Guid("aae6530b-15f1-4469-b5f6-4f69592ad15d"),
                            CiselnikKod = "TYP-OPERACE",
                            CiselnikVerze = "1",
                            Kod = "ZNEPLATNENI",
                            Verze = "1"
                        });
                });

            modelBuilder.Entity("ElektronickePosudky.Domain.Entities.Pacient", b =>
                {
                    b.Property<Guid>("Rid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Adresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatumNarozeni")
                        .HasColumnType("datetime2");

                    b.Property<string>("Doklad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jmeno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pohlavi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prijmeni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Rid");

                    b.ToTable("Pacienti");

                    b.HasData(
                        new
                        {
                            Rid = new Guid("a2e5324b-9ad8-4304-b7b9-e31b56d787f5"),
                            Adresa = "Praha 1, Václavské náměstí 1",
                            DatumNarozeni = new DateTime(1985, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Doklad = "AA123456",
                            Email = "jan.novak@example.com",
                            Jmeno = "Jan",
                            Pohlavi = "M",
                            Prijmeni = "Novák"
                        },
                        new
                        {
                            Rid = new Guid("68eff241-fd51-4b06-9c3c-05799f341d28"),
                            Adresa = "Brno, Náměstí Svobody 10",
                            DatumNarozeni = new DateTime(1990, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Doklad = "BB654321",
                            Email = "marie.svobodova@example.com",
                            Jmeno = "Marie",
                            Pohlavi = "F",
                            Prijmeni = "Svobodová"
                        },
                        new
                        {
                            Rid = new Guid("b362e8f1-99a7-4d68-8b95-ed3606949f25"),
                            Adresa = "Ostrava, Masarykovo náměstí 5",
                            DatumNarozeni = new DateTime(1978, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Doklad = "CC987654",
                            Email = "petr.dvorak@example.com",
                            Jmeno = "Petr",
                            Pohlavi = "M",
                            Prijmeni = "Dvořák"
                        });
                });

            modelBuilder.Entity("ElektronickePosudky.Domain.Entities.PoskytovatelZdravotnickychSluzeb", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Adresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazev")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PoskytovateleZdravotnickychSluzeb");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5373f175-39ae-4082-8345-2434b0fa5d5d"),
                            Adresa = "Praha 2, Karlovo náměstí 10",
                            Ico = "12345678",
                            Nazev = "Zdravotní zařízení s.r.o."
                        },
                        new
                        {
                            Id = new Guid("33bfad8b-102c-42f4-b78a-1ad49bdf5a42"),
                            Adresa = "Brno, Hlavní třída 25",
                            Ico = "87654321",
                            Nazev = "Lékařská klinika Brno a.s."
                        },
                        new
                        {
                            Id = new Guid("bd009c28-b756-416d-9227-341928694587"),
                            Adresa = "Ostrava, Polská 15",
                            Ico = "11223344",
                            Nazev = "Oční ambulance Ostrava"
                        });
                });

            modelBuilder.Entity("ElektronickePosudky.Domain.Entities.PosudekRo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DatumVystaveni")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumVytvoreni")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DruhPosudkuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DruhProhlidkyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("KrzpId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OpakovanyPosudekId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("PlatnostDo")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Rid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid?>("SkupinaZadateleRidicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("StavPosudkuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TypAkceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("VysledekId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DruhPosudkuId");

                    b.HasIndex("DruhProhlidkyId");

                    b.HasIndex("KrzpId");

                    b.HasIndex("Rid");

                    b.HasIndex("SkupinaZadateleRidicId");

                    b.HasIndex("StavPosudkuId");

                    b.HasIndex("TypAkceId");

                    b.HasIndex("VysledekId");

                    b.ToTable("PosudekRos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2fbef511-6099-4bef-b366-75470b13ce1a"),
                            DatumVystaveni = new DateTime(2026, 4, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            DatumVytvoreni = new DateTime(2026, 4, 16, 11, 3, 35, 144, DateTimeKind.Utc).AddTicks(1512),
                            DruhPosudkuId = new Guid("f0c80839-a28f-4698-8ecd-1a8eb7cb7778"),
                            DruhProhlidkyId = new Guid("69e3533b-2d45-4c6d-b8f8-2e2da0900cf5"),
                            KrzpId = new Guid("90755fe5-be32-41cc-9925-27b9648dc6df"),
                            PlatnostDo = new DateTime(2027, 4, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Rid = new Guid("a2e5324b-9ad8-4304-b7b9-e31b56d787f5"),
                            SkupinaZadateleRidicId = new Guid("388f831b-4fb6-42e6-b049-35d14808db0b"),
                            StavPosudkuId = new Guid("91c091e9-2d8a-454a-952e-61a37a6daa0c"),
                            TypAkceId = new Guid("80bfdd5b-19fd-4c59-bd51-382a7cc97815"),
                            VysledekId = new Guid("5dbb39ff-9d53-4c4a-956e-1e5fd88a0987")
                        },
                        new
                        {
                            Id = new Guid("a15fd61e-7c4f-411d-9fd6-7348ef1ce3f3"),
                            DatumVystaveni = new DateTime(2026, 3, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            DatumVytvoreni = new DateTime(2026, 3, 17, 11, 3, 35, 144, DateTimeKind.Utc).AddTicks(1512),
                            DruhPosudkuId = new Guid("f0c80839-a28f-4698-8ecd-1a8eb7cb7778"),
                            DruhProhlidkyId = new Guid("e5f46887-8028-4b62-9286-b2840eef4001"),
                            KrzpId = new Guid("f62d4576-4f54-4c10-90de-b479ea81b433"),
                            PlatnostDo = new DateTime(2026, 10, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Rid = new Guid("68eff241-fd51-4b06-9c3c-05799f341d28"),
                            SkupinaZadateleRidicId = new Guid("93f1f521-9613-47d4-b483-ce27821b7e5a"),
                            StavPosudkuId = new Guid("91c091e9-2d8a-454a-952e-61a37a6daa0c"),
                            TypAkceId = new Guid("80bfdd5b-19fd-4c59-bd51-382a7cc97815"),
                            VysledekId = new Guid("5dbb39ff-9d53-4c4a-956e-1e5fd88a0987")
                        });
                });

            modelBuilder.Entity("ElektronickePosudky.Domain.Entities.PosudekRoHarmonizovanyKod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HarmonizovanyKodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PosudekRoZpusobilostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpresneniText")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HarmonizovanyKodId");

                    b.HasIndex("PosudekRoZpusobilostId");

                    b.ToTable("PosudekRoHarmonizovaneKody");
                });

            modelBuilder.Entity("ElektronickePosudky.Domain.Entities.PosudekRoHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DatumOperace")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("KrzpId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PosudekRoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TypOperaceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("KrzpId");

                    b.HasIndex("PosudekRoId");

                    b.HasIndex("TypOperaceId");

                    b.ToTable("PosudekRoHistories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0b4e6456-bc2e-4d51-992b-0da4fbdd3564"),
                            DatumOperace = new DateTime(2026, 4, 16, 11, 3, 35, 144, DateTimeKind.Utc).AddTicks(1512),
                            KrzpId = new Guid("90755fe5-be32-41cc-9925-27b9648dc6df"),
                            PosudekRoId = new Guid("2fbef511-6099-4bef-b366-75470b13ce1a"),
                            TypOperaceId = new Guid("ea9d54c9-aa27-4aec-bd71-5e74f18318e5")
                        },
                        new
                        {
                            Id = new Guid("d012fd1d-3fb9-4dde-a0a9-a06b3ce03e3f"),
                            DatumOperace = new DateTime(2026, 3, 17, 11, 3, 35, 144, DateTimeKind.Utc).AddTicks(1512),
                            KrzpId = new Guid("f62d4576-4f54-4c10-90de-b479ea81b433"),
                            PosudekRoId = new Guid("a15fd61e-7c4f-411d-9fd6-7348ef1ce3f3"),
                            TypOperaceId = new Guid("ea9d54c9-aa27-4aec-bd71-5e74f18318e5")
                        });
                });

            modelBuilder.Entity("ElektronickePosudky.Domain.Entities.PosudekRoNarodniKod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NarodniKodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PosudekRoZpusobilostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SkupinaRoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpresneniText")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NarodniKodId");

                    b.HasIndex("PosudekRoZpusobilostId");

                    b.HasIndex("SkupinaRoId");

                    b.ToTable("PosudekRoNarodniKody");
                });

            modelBuilder.Entity("ElektronickePosudky.Domain.Entities.PosudekRoSkupina", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PosudekRoZpusobilostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SkupinaRoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PosudekRoZpusobilostId");

                    b.HasIndex("SkupinaRoId");

                    b.ToTable("PosudekRoSkupiny");
                });

            modelBuilder.Entity("ElektronickePosudky.Domain.Entities.PosudekRoZpusobilost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PosudekRoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("SkupinaZadateleRidicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VysledekId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PosudekRoId");

                    b.HasIndex("SkupinaZadateleRidicId");

                    b.HasIndex("VysledekId");

                    b.ToTable("PosudekRoZpusobilosti");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9e0760f2-54af-4cb3-ba3e-c423b4b567bc"),
                            PosudekRoId = new Guid("2fbef511-6099-4bef-b366-75470b13ce1a"),
                            SkupinaZadateleRidicId = new Guid("388f831b-4fb6-42e6-b049-35d14808db0b"),
                            VysledekId = new Guid("5dbb39ff-9d53-4c4a-956e-1e5fd88a0987")
                        },
                        new
                        {
                            Id = new Guid("9d44e4e6-f7cd-41cf-b2a0-289c29faaea4"),
                            PosudekRoId = new Guid("a15fd61e-7c4f-411d-9fd6-7348ef1ce3f3"),
                            SkupinaZadateleRidicId = new Guid("93f1f521-9613-47d4-b483-ce27821b7e5a"),
                            VysledekId = new Guid("5dbb39ff-9d53-4c4a-956e-1e5fd88a0987")
                        });
                });

            modelBuilder.Entity("ElektronickePosudky.Domain.Entities.Translation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CiselnikId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CiselnikPolozkaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CiselnikId");

                    b.HasIndex("CiselnikPolozkaId");

                    b.HasIndex("EntityType", "EntityId", "Language", "PropertyName")
                        .IsUnique();

                    b.ToTable("Translations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("624dc3bf-69ec-4fc8-a68a-fff5813e99f2"),
                            CiselnikId = new Guid("a14bffda-1149-4ec5-b79d-cdda839259c1"),
                            EntityId = new Guid("a14bffda-1149-4ec5-b79d-cdda839259c1"),
                            EntityType = "Ciselnik",
                            Language = "cs-CZ",
                            PropertyName = "Nazev",
                            Value = "Stav posudku"
                        },
                        new
                        {
                            Id = new Guid("e6f1cbbe-e0ca-4e36-b663-cb588cd042ae"),
                            CiselnikId = new Guid("a14bffda-1149-4ec5-b79d-cdda839259c1"),
                            EntityId = new Guid("a14bffda-1149-4ec5-b79d-cdda839259c1"),
                            EntityType = "Ciselnik",
                            Language = "cs-CZ",
                            PropertyName = "Popis",
                            Value = "Stav lékařského posudku"
                        },
                        new
                        {
                            Id = new Guid("224d147d-3abe-4d9d-b98b-d74c92e56d15"),
                            CiselnikId = new Guid("a14bffda-1149-4ec5-b79d-cdda839259c1"),
                            EntityId = new Guid("a14bffda-1149-4ec5-b79d-cdda839259c1"),
                            EntityType = "Ciselnik",
                            Language = "en-US",
                            PropertyName = "Nazev",
                            Value = "Certificate status"
                        },
                        new
                        {
                            Id = new Guid("67a6752d-5aee-41fb-b373-afe29825417b"),
                            CiselnikId = new Guid("a14bffda-1149-4ec5-b79d-cdda839259c1"),
                            EntityId = new Guid("a14bffda-1149-4ec5-b79d-cdda839259c1"),
                            EntityType = "Ciselnik",
                            Language = "en-US",
                            PropertyName = "Popis",
                            Value = "State of the medical certificate"
                        },
                        new
                        {
                            Id = new Guid("ddec5138-afb3-4ed9-8112-690ce0776399"),
                            CiselnikPolozkaId = new Guid("91c091e9-2d8a-454a-952e-61a37a6daa0c"),
                            EntityId = new Guid("91c091e9-2d8a-454a-952e-61a37a6daa0c"),
                            EntityType = "CiselnikPolozka",
                            Language = "cs-CZ",
                            PropertyName = "Nazev",
                            Value = "Platný"
                        },
                        new
                        {
                            Id = new Guid("d5657426-93a7-4ada-8f65-1fa2e7d428f2"),
                            CiselnikPolozkaId = new Guid("91c091e9-2d8a-454a-952e-61a37a6daa0c"),
                            EntityId = new Guid("91c091e9-2d8a-454a-952e-61a37a6daa0c"),
                            EntityType = "CiselnikPolozka",
                            Language = "cs-CZ",
                            PropertyName = "Popis",
                            Value = "Posudek je platný."
                        },
                        new
                        {
                            Id = new Guid("a11ab03b-38cf-441d-b048-742d24d0e40c"),
                            CiselnikPolozkaId = new Guid("91c091e9-2d8a-454a-952e-61a37a6daa0c"),
                            EntityId = new Guid("91c091e9-2d8a-454a-952e-61a37a6daa0c"),
                            EntityType = "CiselnikPolozka",
                            Language = "en-US",
                            PropertyName = "Nazev",
                            Value = "Valid"
                        },
                        new
                        {
                            Id = new Guid("60cf8d89-c0db-4fed-ab0f-e22c862e4cfa"),
                            CiselnikPolozkaId = new Guid("91c091e9-2d8a-454a-952e-61a37a6daa0c"),
                            EntityId = new Guid("91c091e9-2d8a-454a-952e-61a37a6daa0c"),
                            EntityType = "CiselnikPolozka",
                            Language = "en-US",
                            PropertyName = "Popis",
                            Value = "The certificate is valid."
                        },
                        new
                        {
                            Id = new Guid("3435e325-6611-47c8-aabb-53275a1adcf0"),
                            CiselnikPolozkaId = new Guid("06cefa04-8612-4dcf-b196-46d435f1718b"),
                            EntityId = new Guid("06cefa04-8612-4dcf-b196-46d435f1718b"),
                            EntityType = "CiselnikPolozka",
                            Language = "cs-CZ",
                            PropertyName = "Nazev",
                            Value = "Zneplatněný"
                        },
                        new
                        {
                            Id = new Guid("dfd88391-2917-4672-a9d2-1fe87f08586d"),
                            CiselnikPolozkaId = new Guid("06cefa04-8612-4dcf-b196-46d435f1718b"),
                            EntityId = new Guid("06cefa04-8612-4dcf-b196-46d435f1718b"),
                            EntityType = "CiselnikPolozka",
                            Language = "cs-CZ",
                            PropertyName = "Popis",
                            Value = "Posudek byl zneplatněn."
                        },
                        new
                        {
                            Id = new Guid("c9ff9c22-bf7e-484f-905d-ac83dc429a41"),
                            CiselnikPolozkaId = new Guid("06cefa04-8612-4dcf-b196-46d435f1718b"),
                            EntityId = new Guid("06cefa04-8612-4dcf-b196-46d435f1718b"),
                            EntityType = "CiselnikPolozka",
                            Language = "en-US",
                            PropertyName = "Nazev",
                            Value = "Invalidated"
                        },
                        new
                        {
                            Id = new Guid("4148c5ee-8143-449b-a47a-63262c0fae29"),
                            CiselnikPolozkaId = new Guid("06cefa04-8612-4dcf-b196-46d435f1718b"),
                            EntityId = new Guid("06cefa04-8612-4dcf-b196-46d435f1718b"),
                            EntityType = "CiselnikPolozka",
                            Language = "en-US",
                            PropertyName = "Popis",
                            Value = "The certificate has been invalidated."
                        },
                        new
                        {
                            Id = new Guid("0a6d0451-88df-41b9-9f9e-ba0cc3f308e7"),
                            CiselnikId = new Guid("a376442b-a991-4405-81fb-e923e7dde10a"),
                            EntityId = new Guid("a376442b-a991-4405-81fb-e923e7dde10a"),
                            EntityType = "Ciselnik",
                            Language = "cs-CZ",
                            PropertyName = "Nazev",
                            Value = "Druh prohlídky"
                        },
                        new
                        {
                            Id = new Guid("35fded7b-a9db-4143-837f-4df98368454f"),
                            CiselnikId = new Guid("a376442b-a991-4405-81fb-e923e7dde10a"),
                            EntityId = new Guid("a376442b-a991-4405-81fb-e923e7dde10a"),
                            EntityType = "Ciselnik",
                            Language = "cs-CZ",
                            PropertyName = "Popis",
                            Value = "Typ lékařské prohlídky"
                        },
                        new
                        {
                            Id = new Guid("31856937-429f-4bdb-a714-c19729bc4b59"),
                            CiselnikId = new Guid("a376442b-a991-4405-81fb-e923e7dde10a"),
                            EntityId = new Guid("a376442b-a991-4405-81fb-e923e7dde10a"),
                            EntityType = "Ciselnik",
                            Language = "en-US",
                            PropertyName = "Nazev",
                            Value = "Type of examination"
                        },
                        new
                        {
                            Id = new Guid("670cccb2-a2c2-4ee3-9245-7ccfbae0b60f"),
                            CiselnikId = new Guid("a376442b-a991-4405-81fb-e923e7dde10a"),
                            EntityId = new Guid("a376442b-a991-4405-81fb-e923e7dde10a"),
                            EntityType = "Ciselnik",
                            Language = "en-US",
                            PropertyName = "Popis",
                            Value = "Type of medical examination"
                        },
                        new
                        {
                            Id = new Guid("69ef37dc-4ec7-4587-a8e3-8358d1420d2b"),
                            CiselnikPolozkaId = new Guid("69e3533b-2d45-4c6d-b8f8-2e2da0900cf5"),
                            EntityId = new Guid("69e3533b-2d45-4c6d-b8f8-2e2da0900cf5"),
                            EntityType = "CiselnikPolozka",
                            Language = "cs-CZ",
                            PropertyName = "Nazev",
                            Value = "Výchozí prohlídka"
                        },
                        new
                        {
                            Id = new Guid("eea72213-d480-4c06-bffa-07144e6ad5b5"),
                            CiselnikPolozkaId = new Guid("69e3533b-2d45-4c6d-b8f8-2e2da0900cf5"),
                            EntityId = new Guid("69e3533b-2d45-4c6d-b8f8-2e2da0900cf5"),
                            EntityType = "CiselnikPolozka",
                            Language = "cs-CZ",
                            PropertyName = "Popis",
                            Value = "První lékařská prohlídka"
                        },
                        new
                        {
                            Id = new Guid("180a30f6-e421-480e-871d-238ab93857cd"),
                            CiselnikPolozkaId = new Guid("69e3533b-2d45-4c6d-b8f8-2e2da0900cf5"),
                            EntityId = new Guid("69e3533b-2d45-4c6d-b8f8-2e2da0900cf5"),
                            EntityType = "CiselnikPolozka",
                            Language = "en-US",
                            PropertyName = "Nazev",
                            Value = "Initial examination"
                        },
                        new
                        {
                            Id = new Guid("027d1631-f498-4c49-9a8d-0930bc4d9f2d"),
                            CiselnikPolozkaId = new Guid("69e3533b-2d45-4c6d-b8f8-2e2da0900cf5"),
                            EntityId = new Guid("69e3533b-2d45-4c6d-b8f8-2e2da0900cf5"),
                            EntityType = "CiselnikPolozka",
                            Language = "en-US",
                            PropertyName = "Popis",
                            Value = "First medical examination"
                        },
                        new
                        {
                            Id = new Guid("fa9b5f56-a22d-4736-95c4-e7156ed2a701"),
                            CiselnikPolozkaId = new Guid("e5f46887-8028-4b62-9286-b2840eef4001"),
                            EntityId = new Guid("e5f46887-8028-4b62-9286-b2840eef4001"),
                            EntityType = "CiselnikPolozka",
                            Language = "cs-CZ",
                            PropertyName = "Nazev",
                            Value = "Periodická prohlídka"
                        },
                        new
                        {
                            Id = new Guid("aaefffc6-27a5-4715-ba79-f8ecfb1d2a5e"),
                            CiselnikPolozkaId = new Guid("e5f46887-8028-4b62-9286-b2840eef4001"),
                            EntityId = new Guid("e5f46887-8028-4b62-9286-b2840eef4001"),
                            EntityType = "CiselnikPolozka",
                            Language = "cs-CZ",
                            PropertyName = "Popis",
                            Value = "Opakovaná lékařská prohlídka"
                        },
                        new
                        {
                            Id = new Guid("ded6a613-5a99-4225-a34e-03e498d4e55b"),
                            CiselnikPolozkaId = new Guid("e5f46887-8028-4b62-9286-b2840eef4001"),
                            EntityId = new Guid("e5f46887-8028-4b62-9286-b2840eef4001"),
                            EntityType = "CiselnikPolozka",
                            Language = "en-US",
                            PropertyName = "Nazev",
                            Value = "Periodic examination"
                        },
                        new
                        {
                            Id = new Guid("cabce0bf-b8d3-4298-a038-7e17bc7fe760"),
                            CiselnikPolozkaId = new Guid("e5f46887-8028-4b62-9286-b2840eef4001"),
                            EntityId = new Guid("e5f46887-8028-4b62-9286-b2840eef4001"),
                            EntityType = "CiselnikPolozka",
                            Language = "en-US",
                            PropertyName = "Popis",
                            Value = "Repeated medical examination"
                        },
                        new
                        {
                            Id = new Guid("1e0737a3-2b8e-4039-858d-7b37d33ebe96"),
                            CiselnikId = new Guid("aff0c688-3a22-46c8-8404-82c61101d642"),
                            EntityId = new Guid("aff0c688-3a22-46c8-8404-82c61101d642"),
                            EntityType = "Ciselnik",
                            Language = "cs-CZ",
                            PropertyName = "Nazev",
                            Value = "Druh posudku"
                        },
                        new
                        {
                            Id = new Guid("5fb5c057-aa56-43d6-9752-6384f27d5d48"),
                            CiselnikId = new Guid("aff0c688-3a22-46c8-8404-82c61101d642"),
                            EntityId = new Guid("aff0c688-3a22-46c8-8404-82c61101d642"),
                            EntityType = "Ciselnik",
                            Language = "cs-CZ",
                            PropertyName = "Popis",
                            Value = "Typ lékařského posudku"
                        },
                        new
                        {
                            Id = new Guid("d1100919-b486-4482-a1b9-8f7e3d99a13a"),
                            CiselnikId = new Guid("aff0c688-3a22-46c8-8404-82c61101d642"),
                            EntityId = new Guid("aff0c688-3a22-46c8-8404-82c61101d642"),
                            EntityType = "Ciselnik",
                            Language = "en-US",
                            PropertyName = "Nazev",
                            Value = "Type of certificate"
                        },
                        new
                        {
                            Id = new Guid("999c5a85-4490-4cc8-9cce-5235e2cf2a65"),
                            CiselnikId = new Guid("aff0c688-3a22-46c8-8404-82c61101d642"),
                            EntityId = new Guid("aff0c688-3a22-46c8-8404-82c61101d642"),
                            EntityType = "Ciselnik",
                            Language = "en-US",
                            PropertyName = "Popis",
                            Value = "Type of medical certificate"
                        },
                        new
                        {
                            Id = new Guid("07587291-6e91-4569-9eec-738ab04d0a88"),
                            CiselnikPolozkaId = new Guid("f0c80839-a28f-4698-8ecd-1a8eb7cb7778"),
                            EntityId = new Guid("f0c80839-a28f-4698-8ecd-1a8eb7cb7778"),
                            EntityType = "CiselnikPolozka",
                            Language = "cs-CZ",
                            PropertyName = "Nazev",
                            Value = "Řidičský posudek"
                        },
                        new
                        {
                            Id = new Guid("9681e93f-f2db-493c-b5ef-94d6bcfbe968"),
                            CiselnikPolozkaId = new Guid("f0c80839-a28f-4698-8ecd-1a8eb7cb7778"),
                            EntityId = new Guid("f0c80839-a28f-4698-8ecd-1a8eb7cb7778"),
                            EntityType = "CiselnikPolozka",
                            Language = "cs-CZ",
                            PropertyName = "Popis",
                            Value = "Posudek pro řidiče motorových vozidel"
                        },
                        new
                        {
                            Id = new Guid("0478ee82-99dd-46de-b111-187cca3bd963"),
                            CiselnikPolozkaId = new Guid("f0c80839-a28f-4698-8ecd-1a8eb7cb7778"),
                            EntityId = new Guid("f0c80839-a28f-4698-8ecd-1a8eb7cb7778"),
                            EntityType = "CiselnikPolozka",
                            Language = "en-US",
                            PropertyName = "Nazev",
                            Value = "Driver certificate"
                        },
                        new
                        {
                            Id = new Guid("98991224-6e9c-47c9-a197-ea0b67a4c27c"),
                            CiselnikPolozkaId = new Guid("f0c80839-a28f-4698-8ecd-1a8eb7cb7778"),
                            EntityId = new Guid("f0c80839-a28f-4698-8ecd-1a8eb7cb7778"),
                            EntityType = "CiselnikPolozka",
                            Language = "en-US",
                            PropertyName = "Popis",
                            Value = "Certificate for motor vehicle drivers"
                        },
                        new
                        {
                            Id = new Guid("d1b60674-af88-4475-b0af-13a1dfb1d12c"),
                            CiselnikId = new Guid("599ce4bc-4222-42f1-a238-eaed3a4b0abd"),
                            EntityId = new Guid("599ce4bc-4222-42f1-a238-eaed3a4b0abd"),
                            EntityType = "Ciselnik",
                            Language = "cs-CZ",
                            PropertyName = "Nazev",
                            Value = "Výsledek"
                        },
                        new
                        {
                            Id = new Guid("4bcc622d-094d-48b4-b87c-446965265de0"),
                            CiselnikId = new Guid("599ce4bc-4222-42f1-a238-eaed3a4b0abd"),
                            EntityId = new Guid("599ce4bc-4222-42f1-a238-eaed3a4b0abd"),
                            EntityType = "Ciselnik",
                            Language = "cs-CZ",
                            PropertyName = "Popis",
                            Value = "Výsledek lékařského posudku"
                        },
                        new
                        {
                            Id = new Guid("befaa12e-6c93-44ac-a794-8b593830cc82"),
                            CiselnikId = new Guid("599ce4bc-4222-42f1-a238-eaed3a4b0abd"),
                            EntityId = new Guid("599ce4bc-4222-42f1-a238-eaed3a4b0abd"),
                            EntityType = "Ciselnik",
                            Language = "en-US",
                            PropertyName = "Nazev",
                            Value = "Result"
                        },
                        new
                        {
                            Id = new Guid("91579e92-7ad8-478e-8e3b-ea6140a5b7d9"),
                            CiselnikId = new Guid("599ce4bc-4222-42f1-a238-eaed3a4b0abd"),
                            EntityId = new Guid("599ce4bc-4222-42f1-a238-eaed3a4b0abd"),
                            EntityType = "Ciselnik",
                            Language = "en-US",
                            PropertyName = "Popis",
                            Value = "Result of medical certificate"
                        },
                        new
                        {
                            Id = new Guid("91175483-d2fc-4716-acba-08353b081d1d"),
                            CiselnikPolozkaId = new Guid("5dbb39ff-9d53-4c4a-956e-1e5fd88a0987"),
                            EntityId = new Guid("5dbb39ff-9d53-4c4a-956e-1e5fd88a0987"),
                            EntityType = "CiselnikPolozka",
                            Language = "cs-CZ",
                            PropertyName = "Nazev",
                            Value = "Způsobilý"
                        },
                        new
                        {
                            Id = new Guid("c0ec0752-d01c-40b3-b940-a028b22f256e"),
                            CiselnikPolozkaId = new Guid("5dbb39ff-9d53-4c4a-956e-1e5fd88a0987"),
                            EntityId = new Guid("5dbb39ff-9d53-4c4a-956e-1e5fd88a0987"),
                            EntityType = "CiselnikPolozka",
                            Language = "cs-CZ",
                            PropertyName = "Popis",
                            Value = "Pacient je způsobilý k řízení"
                        },
                        new
                        {
                            Id = new Guid("3fae980b-d199-4899-9712-62b69afdc6e3"),
                            CiselnikPolozkaId = new Guid("5dbb39ff-9d53-4c4a-956e-1e5fd88a0987"),
                            EntityId = new Guid("5dbb39ff-9d53-4c4a-956e-1e5fd88a0987"),
                            EntityType = "CiselnikPolozka",
                            Language = "en-US",
                            PropertyName = "Nazev",
                            Value = "Fit"
                        },
                        new
                        {
                            Id = new Guid("9dcaf0f1-f93e-43f3-acbf-5f861e17f31e"),
                            CiselnikPolozkaId = new Guid("5dbb39ff-9d53-4c4a-956e-1e5fd88a0987"),
                            EntityId = new Guid("5dbb39ff-9d53-4c4a-956e-1e5fd88a0987"),
                            EntityType = "CiselnikPolozka",
                            Language = "en-US",
                            PropertyName = "Popis",
                            Value = "Patient is fit to drive"
                        },
                        new
                        {
                            Id = new Guid("d02b8ebe-3334-4d96-bce8-26dcf3f174b3"),
                            CiselnikPolozkaId = new Guid("22743832-b044-4b23-bbb1-a109f7215467"),
                            EntityId = new Guid("22743832-b044-4b23-bbb1-a109f7215467"),
                            EntityType = "CiselnikPolozka",
                            Language = "cs-CZ",
                            PropertyName = "Nazev",
                            Value = "Nezpůsobilý"
                        },
                        new
                        {
                            Id = new Guid("c63682c4-ae65-494d-82d8-86e003308a22"),
                            CiselnikPolozkaId = new Guid("22743832-b044-4b23-bbb1-a109f7215467"),
                            EntityId = new Guid("22743832-b044-4b23-bbb1-a109f7215467"),
                            EntityType = "CiselnikPolozka",
                            Language = "cs-CZ",
                            PropertyName = "Popis",
                            Value = "Pacient není způsobilý k řízení"
                        },
                        new
                        {
                            Id = new Guid("4b8d3135-59ae-4baa-a6f1-287d35502460"),
                            CiselnikPolozkaId = new Guid("22743832-b044-4b23-bbb1-a109f7215467"),
                            EntityId = new Guid("22743832-b044-4b23-bbb1-a109f7215467"),
                            EntityType = "CiselnikPolozka",
                            Language = "en-US",
                            PropertyName = "Nazev",
                            Value = "Unfit"
                        },
                        new
                        {
                            Id = new Guid("a24d9b74-5e02-49d8-bd9a-0662712f188f"),
                            CiselnikPolozkaId = new Guid("22743832-b044-4b23-bbb1-a109f7215467"),
                            EntityId = new Guid("22743832-b044-4b23-bbb1-a109f7215467"),
                            EntityType = "CiselnikPolozka",
                            Language = "en-US",
                            PropertyName = "Popis",
                            Value = "Patient is unfit to drive"
                        },
                        new
                        {
                            Id = new Guid("f851bcb7-6926-43b8-9596-68b1ed487300"),
                            CiselnikId = new Guid("9c599c83-1898-4d8a-aa18-3f867f8772a4"),
                            EntityId = new Guid("9c599c83-1898-4d8a-aa18-3f867f8772a4"),
                            EntityType = "Ciselnik",
                            Language = "cs-CZ",
                            PropertyName = "Nazev",
                            Value = "Skupina žadatele řidič"
                        },
                        new
                        {
                            Id = new Guid("4c7f5378-dc81-4cc0-87b8-4ab1e14ac5fc"),
                            CiselnikId = new Guid("9c599c83-1898-4d8a-aa18-3f867f8772a4"),
                            EntityId = new Guid("9c599c83-1898-4d8a-aa18-3f867f8772a4"),
                            EntityType = "Ciselnik",
                            Language = "cs-CZ",
                            PropertyName = "Popis",
                            Value = "Skupina řidičského oprávnění"
                        },
                        new
                        {
                            Id = new Guid("ec206853-eaa4-47d8-9f05-bfe23fdcf42f"),
                            CiselnikId = new Guid("9c599c83-1898-4d8a-aa18-3f867f8772a4"),
                            EntityId = new Guid("9c599c83-1898-4d8a-aa18-3f867f8772a4"),
                            EntityType = "Ciselnik",
                            Language = "en-US",
                            PropertyName = "Nazev",
                            Value = "Driver applicant group"
                        },
                        new
                        {
                            Id = new Guid("55977a83-23a1-4a5c-8b96-53f5f6e221b9"),
                            CiselnikId = new Guid("9c599c83-1898-4d8a-aa18-3f867f8772a4"),
                            EntityId = new Guid("9c599c83-1898-4d8a-aa18-3f867f8772a4"),
                            EntityType = "Ciselnik",
                            Language = "en-US",
                            PropertyName = "Popis",
                            Value = "Driver license group"
                        },
                        new
                        {
                            Id = new Guid("231e6ed5-3808-4e1a-a793-d34b7d015a05"),
                            CiselnikPolozkaId = new Guid("93f1f521-9613-47d4-b483-ce27821b7e5a"),
                            EntityId = new Guid("93f1f521-9613-47d4-b483-ce27821b7e5a"),
                            EntityType = "CiselnikPolozka",
                            Language = "cs-CZ",
                            PropertyName = "Nazev",
                            Value = "Skupina A"
                        },
                        new
                        {
                            Id = new Guid("b589dc61-76ab-441a-84b4-073fd444bb8e"),
                            CiselnikPolozkaId = new Guid("93f1f521-9613-47d4-b483-ce27821b7e5a"),
                            EntityId = new Guid("93f1f521-9613-47d4-b483-ce27821b7e5a"),
                            EntityType = "CiselnikPolozka",
                            Language = "cs-CZ",
                            PropertyName = "Popis",
                            Value = "Řidičská skupina A (motocykly)"
                        },
                        new
                        {
                            Id = new Guid("472c0643-f333-452d-8462-3603d6aa0e5c"),
                            CiselnikPolozkaId = new Guid("93f1f521-9613-47d4-b483-ce27821b7e5a"),
                            EntityId = new Guid("93f1f521-9613-47d4-b483-ce27821b7e5a"),
                            EntityType = "CiselnikPolozka",
                            Language = "en-US",
                            PropertyName = "Nazev",
                            Value = "Group A"
                        },
                        new
                        {
                            Id = new Guid("033ff235-6965-4b10-8604-7839b8d7e817"),
                            CiselnikPolozkaId = new Guid("93f1f521-9613-47d4-b483-ce27821b7e5a"),
                            EntityId = new Guid("93f1f521-9613-47d4-b483-ce27821b7e5a"),
                            EntityType = "CiselnikPolozka",
                            Language = "en-US",
                            PropertyName = "Popis",
                            Value = "Driver group A (motorcycles)"
                        },
                        new
                        {
                            Id = new Guid("8e1eeb73-7a0a-400d-9fc9-093ce712a974"),
                            CiselnikPolozkaId = new Guid("388f831b-4fb6-42e6-b049-35d14808db0b"),
                            EntityId = new Guid("388f831b-4fb6-42e6-b049-35d14808db0b"),
                            EntityType = "CiselnikPolozka",
                            Language = "cs-CZ",
                            PropertyName = "Nazev",
                            Value = "Skupina B"
                        },
                        new
                        {
                            Id = new Guid("fc9c1ccf-afd2-4f75-a17e-98df8d7f95c3"),
                            CiselnikPolozkaId = new Guid("388f831b-4fb6-42e6-b049-35d14808db0b"),
                            EntityId = new Guid("388f831b-4fb6-42e6-b049-35d14808db0b"),
                            EntityType = "CiselnikPolozka",
                            Language = "cs-CZ",
                            PropertyName = "Popis",
                            Value = "Řidičská skupina B (automobily)"
                        },
                        new
                        {
                            Id = new Guid("cedbb8df-5004-420b-91b6-2323b19a5bb7"),
                            CiselnikPolozkaId = new Guid("388f831b-4fb6-42e6-b049-35d14808db0b"),
                            EntityId = new Guid("388f831b-4fb6-42e6-b049-35d14808db0b"),
                            EntityType = "CiselnikPolozka",
                            Language = "en-US",
                            PropertyName = "Nazev",
                            Value = "Group B"
                        },
                        new
                        {
                            Id = new Guid("739aef0e-9ece-43cc-960a-a4ed8076cb0c"),
                            CiselnikPolozkaId = new Guid("388f831b-4fb6-42e6-b049-35d14808db0b"),
                            EntityId = new Guid("388f831b-4fb6-42e6-b049-35d14808db0b"),
                            EntityType = "CiselnikPolozka",
                            Language = "en-US",
                            PropertyName = "Popis",
                            Value = "Driver group B (cars)"
                        },
                        new
                        {
                            Id = new Guid("8922593c-d0a8-4f2a-81d6-061f3c85fedc"),
                            CiselnikId = new Guid("278605a9-2aa3-42d4-babe-f3d177fd2905"),
                            EntityId = new Guid("278605a9-2aa3-42d4-babe-f3d177fd2905"),
                            EntityType = "Ciselnik",
                            Language = "cs-CZ",
                            PropertyName = "Nazev",
                            Value = "Odbornost"
                        },
                        new
                        {
                            Id = new Guid("d0c1d04d-3696-4b3b-a68b-68894660fc7b"),
                            CiselnikId = new Guid("278605a9-2aa3-42d4-babe-f3d177fd2905"),
                            EntityId = new Guid("278605a9-2aa3-42d4-babe-f3d177fd2905"),
                            EntityType = "Ciselnik",
                            Language = "cs-CZ",
                            PropertyName = "Popis",
                            Value = "Lékařská odbornost"
                        },
                        new
                        {
                            Id = new Guid("9807fec7-563d-46a3-bca1-6622de371add"),
                            CiselnikId = new Guid("278605a9-2aa3-42d4-babe-f3d177fd2905"),
                            EntityId = new Guid("278605a9-2aa3-42d4-babe-f3d177fd2905"),
                            EntityType = "Ciselnik",
                            Language = "en-US",
                            PropertyName = "Nazev",
                            Value = "Specialty"
                        },
                        new
                        {
                            Id = new Guid("4bf4e35f-6f1b-420e-991f-7f84d2759a6b"),
                            CiselnikId = new Guid("278605a9-2aa3-42d4-babe-f3d177fd2905"),
                            EntityId = new Guid("278605a9-2aa3-42d4-babe-f3d177fd2905"),
                            EntityType = "Ciselnik",
                            Language = "en-US",
                            PropertyName = "Popis",
                            Value = "Medical specialty"
                        },
                        new
                        {
                            Id = new Guid("c0eb025d-0d26-40fb-88f7-03f51beb2762"),
                            CiselnikPolozkaId = new Guid("82f7d36c-abd7-4e81-b29a-59873ac932a1"),
                            EntityId = new Guid("82f7d36c-abd7-4e81-b29a-59873ac932a1"),
                            EntityType = "CiselnikPolozka",
                            Language = "cs-CZ",
                            PropertyName = "Nazev",
                            Value = "Interní lékař"
                        },
                        new
                        {
                            Id = new Guid("68d74b78-276b-4ee5-9696-2eefc53ff11f"),
                            CiselnikPolozkaId = new Guid("82f7d36c-abd7-4e81-b29a-59873ac932a1"),
                            EntityId = new Guid("82f7d36c-abd7-4e81-b29a-59873ac932a1"),
                            EntityType = "CiselnikPolozka",
                            Language = "cs-CZ",
                            PropertyName = "Popis",
                            Value = "Lékař interního lékařství"
                        },
                        new
                        {
                            Id = new Guid("503dc0b1-d17f-424e-9c04-c83f1b9453dd"),
                            CiselnikPolozkaId = new Guid("82f7d36c-abd7-4e81-b29a-59873ac932a1"),
                            EntityId = new Guid("82f7d36c-abd7-4e81-b29a-59873ac932a1"),
                            EntityType = "CiselnikPolozka",
                            Language = "en-US",
                            PropertyName = "Nazev",
                            Value = "Internal medicine"
                        },
                        new
                        {
                            Id = new Guid("d0038089-a614-439a-8fb3-81d42b784b1f"),
                            CiselnikPolozkaId = new Guid("82f7d36c-abd7-4e81-b29a-59873ac932a1"),
                            EntityId = new Guid("82f7d36c-abd7-4e81-b29a-59873ac932a1"),
                            EntityType = "CiselnikPolozka",
                            Language = "en-US",
                            PropertyName = "Popis",
                            Value = "Internal medicine physician"
                        },
                        new
                        {
                            Id = new Guid("2e51e2d2-a07e-465a-8b52-0cf167bf73b1"),
                            CiselnikPolozkaId = new Guid("d8270f50-c7ad-4653-b893-b5897f9d52b0"),
                            EntityId = new Guid("d8270f50-c7ad-4653-b893-b5897f9d52b0"),
                            EntityType = "CiselnikPolozka",
                            Language = "cs-CZ",
                            PropertyName = "Nazev",
                            Value = "Oční lékař"
                        },
                        new
                        {
                            Id = new Guid("65d16cb8-1a1f-4f99-ac35-90d9c8c56e92"),
                            CiselnikPolozkaId = new Guid("d8270f50-c7ad-4653-b893-b5897f9d52b0"),
                            EntityId = new Guid("d8270f50-c7ad-4653-b893-b5897f9d52b0"),
                            EntityType = "CiselnikPolozka",
                            Language = "cs-CZ",
                            PropertyName = "Popis",
                            Value = "Oční lékař (oftalmolog)"
                        },
                        new
                        {
                            Id = new Guid("716dfab9-361b-43ee-a6f1-32f99111c746"),
                            CiselnikPolozkaId = new Guid("d8270f50-c7ad-4653-b893-b5897f9d52b0"),
                            EntityId = new Guid("d8270f50-c7ad-4653-b893-b5897f9d52b0"),
                            EntityType = "CiselnikPolozka",
                            Language = "en-US",
                            PropertyName = "Nazev",
                            Value = "Ophthalmologist"
                        },
                        new
                        {
                            Id = new Guid("e1fb0372-71b8-4c78-bb4a-51f23fc482ef"),
                            CiselnikPolozkaId = new Guid("d8270f50-c7ad-4653-b893-b5897f9d52b0"),
                            EntityId = new Guid("d8270f50-c7ad-4653-b893-b5897f9d52b0"),
                            EntityType = "CiselnikPolozka",
                            Language = "en-US",
                            PropertyName = "Popis",
                            Value = "Eye physician (ophthalmologist)"
                        },
                        new
                        {
                            Id = new Guid("e3970c58-98f6-409d-be75-902da3817ce8"),
                            CiselnikId = new Guid("d8142494-0f9d-4f6c-b1aa-2a42d071b5e8"),
                            EntityId = new Guid("d8142494-0f9d-4f6c-b1aa-2a42d071b5e8"),
                            EntityType = "Ciselnik",
                            Language = "cs-CZ",
                            PropertyName = "Nazev",
                            Value = "Typ akce"
                        },
                        new
                        {
                            Id = new Guid("9f87bbab-541e-43c2-b277-8ecc19cd42e9"),
                            CiselnikId = new Guid("d8142494-0f9d-4f6c-b1aa-2a42d071b5e8"),
                            EntityId = new Guid("d8142494-0f9d-4f6c-b1aa-2a42d071b5e8"),
                            EntityType = "Ciselnik",
                            Language = "cs-CZ",
                            PropertyName = "Popis",
                            Value = "Typ akce s posudkem"
                        },
                        new
                        {
                            Id = new Guid("6dae6354-7952-4709-8c78-c484d560e678"),
                            CiselnikId = new Guid("d8142494-0f9d-4f6c-b1aa-2a42d071b5e8"),
                            EntityId = new Guid("d8142494-0f9d-4f6c-b1aa-2a42d071b5e8"),
                            EntityType = "Ciselnik",
                            Language = "en-US",
                            PropertyName = "Nazev",
                            Value = "Type of action"
                        },
                        new
                        {
                            Id = new Guid("5a0c662b-edee-4ef8-909b-7d21220f81e5"),
                            CiselnikId = new Guid("d8142494-0f9d-4f6c-b1aa-2a42d071b5e8"),
                            EntityId = new Guid("d8142494-0f9d-4f6c-b1aa-2a42d071b5e8"),
                            EntityType = "Ciselnik",
                            Language = "en-US",
                            PropertyName = "Popis",
                            Value = "Type of action with certificate"
                        },
                        new
                        {
                            Id = new Guid("95d15029-a56e-42d3-94d0-e144cf153de6"),
                            CiselnikPolozkaId = new Guid("80bfdd5b-19fd-4c59-bd51-382a7cc97815"),
                            EntityId = new Guid("80bfdd5b-19fd-4c59-bd51-382a7cc97815"),
                            EntityType = "CiselnikPolozka",
                            Language = "cs-CZ",
                            PropertyName = "Nazev",
                            Value = "Vydání"
                        },
                        new
                        {
                            Id = new Guid("a64d1eff-2e67-454c-b30c-18261a89a84f"),
                            CiselnikPolozkaId = new Guid("80bfdd5b-19fd-4c59-bd51-382a7cc97815"),
                            EntityId = new Guid("80bfdd5b-19fd-4c59-bd51-382a7cc97815"),
                            EntityType = "CiselnikPolozka",
                            Language = "cs-CZ",
                            PropertyName = "Popis",
                            Value = "Vydání nového posudku"
                        },
                        new
                        {
                            Id = new Guid("d3e32bec-ceb0-495e-90ed-1a477dff07a1"),
                            CiselnikPolozkaId = new Guid("80bfdd5b-19fd-4c59-bd51-382a7cc97815"),
                            EntityId = new Guid("80bfdd5b-19fd-4c59-bd51-382a7cc97815"),
                            EntityType = "CiselnikPolozka",
                            Language = "en-US",
                            PropertyName = "Nazev",
                            Value = "Issuance"
                        },
                        new
                        {
                            Id = new Guid("573b75f2-db88-4e2d-812f-36a743f091ac"),
                            CiselnikPolozkaId = new Guid("80bfdd5b-19fd-4c59-bd51-382a7cc97815"),
                            EntityId = new Guid("80bfdd5b-19fd-4c59-bd51-382a7cc97815"),
                            EntityType = "CiselnikPolozka",
                            Language = "en-US",
                            PropertyName = "Popis",
                            Value = "Issuance of new certificate"
                        },
                        new
                        {
                            Id = new Guid("31ae4019-93aa-4c96-8e42-ea105b9b8b5c"),
                            CiselnikId = new Guid("aae6530b-15f1-4469-b5f6-4f69592ad15d"),
                            EntityId = new Guid("aae6530b-15f1-4469-b5f6-4f69592ad15d"),
                            EntityType = "Ciselnik",
                            Language = "cs-CZ",
                            PropertyName = "Nazev",
                            Value = "Typ operace"
                        },
                        new
                        {
                            Id = new Guid("390b91d4-d284-42a6-9f50-cc74ecf008e6"),
                            CiselnikId = new Guid("aae6530b-15f1-4469-b5f6-4f69592ad15d"),
                            EntityId = new Guid("aae6530b-15f1-4469-b5f6-4f69592ad15d"),
                            EntityType = "Ciselnik",
                            Language = "cs-CZ",
                            PropertyName = "Popis",
                            Value = "Typ operace v historii"
                        },
                        new
                        {
                            Id = new Guid("ca1bca16-12d4-4a26-8f8a-b00e0a37fd52"),
                            CiselnikId = new Guid("aae6530b-15f1-4469-b5f6-4f69592ad15d"),
                            EntityId = new Guid("aae6530b-15f1-4469-b5f6-4f69592ad15d"),
                            EntityType = "Ciselnik",
                            Language = "en-US",
                            PropertyName = "Nazev",
                            Value = "Operation type"
                        },
                        new
                        {
                            Id = new Guid("86eaad43-638e-404b-b7de-a4f71a4c6f59"),
                            CiselnikId = new Guid("aae6530b-15f1-4469-b5f6-4f69592ad15d"),
                            EntityId = new Guid("aae6530b-15f1-4469-b5f6-4f69592ad15d"),
                            EntityType = "Ciselnik",
                            Language = "en-US",
                            PropertyName = "Popis",
                            Value = "Type of operation in history"
                        },
                        new
                        {
                            Id = new Guid("5850d2db-ed05-4dd8-98c9-2a29b13b2bce"),
                            CiselnikPolozkaId = new Guid("ea9d54c9-aa27-4aec-bd71-5e74f18318e5"),
                            EntityId = new Guid("ea9d54c9-aa27-4aec-bd71-5e74f18318e5"),
                            EntityType = "CiselnikPolozka",
                            Language = "cs-CZ",
                            PropertyName = "Nazev",
                            Value = "Vytvoření"
                        },
                        new
                        {
                            Id = new Guid("8c4de44e-806b-401e-8947-d35d703b00ce"),
                            CiselnikPolozkaId = new Guid("ea9d54c9-aa27-4aec-bd71-5e74f18318e5"),
                            EntityId = new Guid("ea9d54c9-aa27-4aec-bd71-5e74f18318e5"),
                            EntityType = "CiselnikPolozka",
                            Language = "cs-CZ",
                            PropertyName = "Popis",
                            Value = "Vytvoření posudku"
                        },
                        new
                        {
                            Id = new Guid("e0680f53-3ac2-4a0b-8258-4935b21c132f"),
                            CiselnikPolozkaId = new Guid("ea9d54c9-aa27-4aec-bd71-5e74f18318e5"),
                            EntityId = new Guid("ea9d54c9-aa27-4aec-bd71-5e74f18318e5"),
                            EntityType = "CiselnikPolozka",
                            Language = "en-US",
                            PropertyName = "Nazev",
                            Value = "Creation"
                        },
                        new
                        {
                            Id = new Guid("b8f8478e-4dac-4ce6-8577-b356cde69e1c"),
                            CiselnikPolozkaId = new Guid("ea9d54c9-aa27-4aec-bd71-5e74f18318e5"),
                            EntityId = new Guid("ea9d54c9-aa27-4aec-bd71-5e74f18318e5"),
                            EntityType = "CiselnikPolozka",
                            Language = "en-US",
                            PropertyName = "Popis",
                            Value = "Certificate creation"
                        },
                        new
                        {
                            Id = new Guid("a15d2f3c-f850-4e4d-92bb-d4264b34696a"),
                            CiselnikPolozkaId = new Guid("ea4b809d-35eb-47c7-bbf8-91b4b3528914"),
                            EntityId = new Guid("ea4b809d-35eb-47c7-bbf8-91b4b3528914"),
                            EntityType = "CiselnikPolozka",
                            Language = "cs-CZ",
                            PropertyName = "Nazev",
                            Value = "Zneplatnění"
                        },
                        new
                        {
                            Id = new Guid("5bb55986-3a35-4f5c-a4a5-2f8f196986f1"),
                            CiselnikPolozkaId = new Guid("ea4b809d-35eb-47c7-bbf8-91b4b3528914"),
                            EntityId = new Guid("ea4b809d-35eb-47c7-bbf8-91b4b3528914"),
                            EntityType = "CiselnikPolozka",
                            Language = "cs-CZ",
                            PropertyName = "Popis",
                            Value = "Zneplatnění posudku"
                        },
                        new
                        {
                            Id = new Guid("c14bf82f-fb0f-440c-94b9-c79d65bd8470"),
                            CiselnikPolozkaId = new Guid("ea4b809d-35eb-47c7-bbf8-91b4b3528914"),
                            EntityId = new Guid("ea4b809d-35eb-47c7-bbf8-91b4b3528914"),
                            EntityType = "CiselnikPolozka",
                            Language = "en-US",
                            PropertyName = "Nazev",
                            Value = "Invalidation"
                        },
                        new
                        {
                            Id = new Guid("c6960894-8698-432b-b0f2-82cde98e8e4d"),
                            CiselnikPolozkaId = new Guid("ea4b809d-35eb-47c7-bbf8-91b4b3528914"),
                            EntityId = new Guid("ea4b809d-35eb-47c7-bbf8-91b4b3528914"),
                            EntityType = "CiselnikPolozka",
                            Language = "en-US",
                            PropertyName = "Popis",
                            Value = "Certificate invalidation"
                        });
                });

            modelBuilder.Entity("ElektronickePosudky.Domain.Entities.ZdravotnickyPracovnik", b =>
                {
                    b.Property<Guid>("KrzpId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Jmeno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OdbornostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PoskytovatelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Prijmeni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KrzpId");

                    b.HasIndex("OdbornostId");

                    b.HasIndex("PoskytovatelId");

                    b.ToTable("ZdravotnickyPracovnici");

                    b.HasData(
                        new
                        {
                            KrzpId = new Guid("90755fe5-be32-41cc-9925-27b9648dc6df"),
                            Jmeno = "Petr",
                            OdbornostId = new Guid("82f7d36c-abd7-4e81-b29a-59873ac932a1"),
                            PoskytovatelId = new Guid("5373f175-39ae-4082-8345-2434b0fa5d5d"),
                            Prijmeni = "Dvořák"
                        },
                        new
                        {
                            KrzpId = new Guid("f62d4576-4f54-4c10-90de-b479ea81b433"),
                            Jmeno = "Anna",
                            OdbornostId = new Guid("d8270f50-c7ad-4653-b893-b5897f9d52b0"),
                            PoskytovatelId = new Guid("33bfad8b-102c-42f4-b78a-1ad49bdf5a42"),
                            Prijmeni = "Novotná"
                        },
                        new
                        {
                            KrzpId = new Guid("613b2812-75f2-4dff-85c9-f884bc479385"),
                            Jmeno = "Michal",
                            OdbornostId = new Guid("82f7d36c-abd7-4e81-b29a-59873ac932a1"),
                            PoskytovatelId = new Guid("bd009c28-b756-416d-9227-341928694587"),
                            Prijmeni = "Procházka"
                        });
                });

            modelBuilder.Entity("ElektronickePosudky.Domain.Entities.CiselnikPolozka", b =>
                {
                    b.HasOne("ElektronickePosudky.Domain.Entities.Ciselnik", "Ciselnik")
                        .WithMany("Items")
                        .HasForeignKey("CiselnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElektronickePosudky.Domain.Entities.CiselnikPolozka", "Rodic")
                        .WithMany()
                        .HasForeignKey("RodicId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Ciselnik");

                    b.Navigation("Rodic");
                });

            modelBuilder.Entity("ElektronickePosudky.Domain.Entities.PosudekRo", b =>
                {
                    b.HasOne("ElektronickePosudky.Domain.Entities.CiselnikPolozka", "DruhPosudku")
                        .WithMany()
                        .HasForeignKey("DruhPosudkuId");

                    b.HasOne("ElektronickePosudky.Domain.Entities.CiselnikPolozka", "DruhProhlidky")
                        .WithMany()
                        .HasForeignKey("DruhProhlidkyId");

                    b.HasOne("ElektronickePosudky.Domain.Entities.ZdravotnickyPracovnik", "Lekar")
                        .WithMany()
                        .HasForeignKey("KrzpId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ElektronickePosudky.Domain.Entities.Pacient", "Pacient")
                        .WithMany()
                        .HasForeignKey("Rid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ElektronickePosudky.Domain.Entities.CiselnikPolozka", "SkupinaZadateleRidic")
                        .WithMany()
                        .HasForeignKey("SkupinaZadateleRidicId");

                    b.HasOne("ElektronickePosudky.Domain.Entities.CiselnikPolozka", "StavPosudku")
                        .WithMany()
                        .HasForeignKey("StavPosudkuId");

                    b.HasOne("ElektronickePosudky.Domain.Entities.CiselnikPolozka", "TypAkce")
                        .WithMany()
                        .HasForeignKey("TypAkceId");

                    b.HasOne("ElektronickePosudky.Domain.Entities.CiselnikPolozka", "Vysledek")
                        .WithMany()
                        .HasForeignKey("VysledekId");

                    b.Navigation("DruhPosudku");

                    b.Navigation("DruhProhlidky");

                    b.Navigation("Lekar");

                    b.Navigation("Pacient");

                    b.Navigation("SkupinaZadateleRidic");

                    b.Navigation("StavPosudku");

                    b.Navigation("TypAkce");

                    b.Navigation("Vysledek");
                });

            modelBuilder.Entity("ElektronickePosudky.Domain.Entities.PosudekRoHarmonizovanyKod", b =>
                {
                    b.HasOne("ElektronickePosudky.Domain.Entities.CiselnikPolozka", "HarmonizovanyKod")
                        .WithMany()
                        .HasForeignKey("HarmonizovanyKodId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ElektronickePosudky.Domain.Entities.PosudekRoZpusobilost", "PosudekRoZpusobilost")
                        .WithMany("HarmonizovaneKody")
                        .HasForeignKey("PosudekRoZpusobilostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HarmonizovanyKod");

                    b.Navigation("PosudekRoZpusobilost");
                });

            modelBuilder.Entity("ElektronickePosudky.Domain.Entities.PosudekRoHistory", b =>
                {
                    b.HasOne("ElektronickePosudky.Domain.Entities.ZdravotnickyPracovnik", "Lekar")
                        .WithMany()
                        .HasForeignKey("KrzpId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ElektronickePosudky.Domain.Entities.PosudekRo", "PosudekRo")
                        .WithMany("Historie")
                        .HasForeignKey("PosudekRoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElektronickePosudky.Domain.Entities.CiselnikPolozka", "TypOperace")
                        .WithMany()
                        .HasForeignKey("TypOperaceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Lekar");

                    b.Navigation("PosudekRo");

                    b.Navigation("TypOperace");
                });

            modelBuilder.Entity("ElektronickePosudky.Domain.Entities.PosudekRoNarodniKod", b =>
                {
                    b.HasOne("ElektronickePosudky.Domain.Entities.CiselnikPolozka", "NarodniKod")
                        .WithMany()
                        .HasForeignKey("NarodniKodId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ElektronickePosudky.Domain.Entities.PosudekRoZpusobilost", "PosudekRoZpusobilost")
                        .WithMany("NarodniKody")
                        .HasForeignKey("PosudekRoZpusobilostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElektronickePosudky.Domain.Entities.CiselnikPolozka", "SkupinaRo")
                        .WithMany()
                        .HasForeignKey("SkupinaRoId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("NarodniKod");

                    b.Navigation("PosudekRoZpusobilost");

                    b.Navigation("SkupinaRo");
                });

            modelBuilder.Entity("ElektronickePosudky.Domain.Entities.PosudekRoSkupina", b =>
                {
                    b.HasOne("ElektronickePosudky.Domain.Entities.PosudekRoZpusobilost", "PosudekRoZpusobilost")
                        .WithMany("SkupinyRidicskehoOpravneni")
                        .HasForeignKey("PosudekRoZpusobilostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElektronickePosudky.Domain.Entities.CiselnikPolozka", "SkupinaRo")
                        .WithMany()
                        .HasForeignKey("SkupinaRoId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("PosudekRoZpusobilost");

                    b.Navigation("SkupinaRo");
                });

            modelBuilder.Entity("ElektronickePosudky.Domain.Entities.PosudekRoZpusobilost", b =>
                {
                    b.HasOne("ElektronickePosudky.Domain.Entities.PosudekRo", "PosudekRo")
                        .WithMany("Zpusobilosti")
                        .HasForeignKey("PosudekRoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElektronickePosudky.Domain.Entities.CiselnikPolozka", "SkupinaZadateleRidic")
                        .WithMany()
                        .HasForeignKey("SkupinaZadateleRidicId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ElektronickePosudky.Domain.Entities.CiselnikPolozka", "Vysledek")
                        .WithMany()
                        .HasForeignKey("VysledekId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("PosudekRo");

                    b.Navigation("SkupinaZadateleRidic");

                    b.Navigation("Vysledek");
                });

            modelBuilder.Entity("ElektronickePosudky.Domain.Entities.Translation", b =>
                {
                    b.HasOne("ElektronickePosudky.Domain.Entities.Ciselnik", "Ciselnik")
                        .WithMany("Translations")
                        .HasForeignKey("CiselnikId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ElektronickePosudky.Domain.Entities.CiselnikPolozka", "CiselnikPolozka")
                        .WithMany("Translations")
                        .HasForeignKey("CiselnikPolozkaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Ciselnik");

                    b.Navigation("CiselnikPolozka");
                });

            modelBuilder.Entity("ElektronickePosudky.Domain.Entities.ZdravotnickyPracovnik", b =>
                {
                    b.HasOne("ElektronickePosudky.Domain.Entities.CiselnikPolozka", "Odbornost")
                        .WithMany()
                        .HasForeignKey("OdbornostId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ElektronickePosudky.Domain.Entities.PoskytovatelZdravotnickychSluzeb", "Poskytovatel")
                        .WithMany("Lekary")
                        .HasForeignKey("PoskytovatelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Odbornost");

                    b.Navigation("Poskytovatel");
                });

            modelBuilder.Entity("ElektronickePosudky.Domain.Entities.Ciselnik", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("ElektronickePosudky.Domain.Entities.CiselnikPolozka", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("ElektronickePosudky.Domain.Entities.PoskytovatelZdravotnickychSluzeb", b =>
                {
                    b.Navigation("Lekary");
                });

            modelBuilder.Entity("ElektronickePosudky.Domain.Entities.PosudekRo", b =>
                {
                    b.Navigation("Historie");

                    b.Navigation("Zpusobilosti");
                });

            modelBuilder.Entity("ElektronickePosudky.Domain.Entities.PosudekRoZpusobilost", b =>
                {
                    b.Navigation("HarmonizovaneKody");

                    b.Navigation("NarodniKody");

                    b.Navigation("SkupinyRidicskehoOpravneni");
                });
#pragma warning restore 612, 618
        }
    }
}
